# Generated by Django 5.2.1 on 2025-06-29 19:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomprod', models.CharField(max_length=200)),
                ('DescripcionProd', models.CharField(blank=True, max_length=200)),
                ('Stock', models.PositiveIntegerField(default=0)),
                ('FotoProd', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.BooleanField(default=False)),
                ('FechaPub', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTienda', models.CharField(max_length=200)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('DescripcionTienda', models.TextField(blank=True)),
                ('Cant_productos', models.PositiveIntegerField(default=0)),
                ('Cant_seguidores', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCategoria',
            fields=[
                ('NomCat', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='vacio_', max_length=100, verbose_name='Apellido')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tienda', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocategoria', verbose_name='Tipo de Categoria'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='Propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', unique=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='SeguimientoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tienda', verbose_name='Tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'tienda'], name='api_seguimi_usuario_9536aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoDeseado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='Usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'producto'], name='api_product_usuario_a5fae7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'carrito', 'preference_id'], name='api_pago_usuario_2041e0_idx')],
            },
        ),
    ]
